Copy .github workflow from master

diff --git a/.github/workflows/reusable-build.yaml b/.github/workflows/reusable-build.yaml
--- a/.github/workflows/reusable-build.yaml
+++ b/.github/workflows/reusable-build.yaml
@@ -45,10 +45,28 @@ jobs:
       BUILD_REGISTRY_URL: ${{ inputs.registry_url || vars.REGISTRY_URL }}
 
     steps:
+      - name: Input Validation
+        run: |
+          exit_code=0
+
+          if [ -z "${BUILD_REGISTRY}" ]; then
+            echo "::error title=Configuration Error::BUILD_REGISTRY is empty."
+            echo "Please ensure 'registry' input is set or 'REGISTRY' variable is configured in the ${{ inputs.environment }} environment."
+            exit_code=1
+          fi
+
+          if [ -z "${BUILD_REGISTRY_URL}" ]; then
+            echo "::error title=Configuration Error::BUILD_REGISTRY_URL is empty."
+            echo "Please ensure 'registry_url' input is set or 'REGISTRY_URL' variable is configured in the ${{ inputs.environment }} environment."
+            exit_code=1
+          fi
+
+          exit "${exit_code}"
+
       - uses: docker/setup-buildx-action@v3
       - uses: docker/login-action@v3
         with:
-          registry: ${{ inputs.registry }}
+          registry: ${{ env.BUILD_REGISTRY }}
           username: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
           password: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}
       - uses: docker/build-push-action@v4
@@ -61,8 +79,8 @@ jobs:
             GITHUB_SHA=${{ github.sha }}
           target: app
           tags: |
-            ${{ vars.REGISTRY_URL }}:latest
-            ${{ vars.REGISTRY_URL }}:git-${{ github.sha }}
+            ${{ env.BUILD_REGISTRY_URL }}:latest
+            ${{ env.BUILD_REGISTRY_URL }}:git-${{ github.sha }}
           push: ${{ inputs.push }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
